### PR TITLE
fix: enable management policies

### LINKED ISSUE #206: managementPolicies is not supported
### What problem are you facing?

The marketplace API documentation lists `managementPolicies` as a valid option. This is not available in the CRDs though.

[Marketplace link](https://marketplace.upbound.io/providers/crossplane-contrib/provider-sql/v0.10.0/resources/postgresql.sql.crossplane.io/Database/v1alpha1#doc:spec-managementPolicies)

```
$ k explain "roles.postgresql.sql.crossplane.io".spec
GROUP:      postgresql.sql.crossplane.io
KIND:       Role
VERSION:    v1alpha1

FIELD: spec <Object>


DESCRIPTION:
    A RoleSpec defines the desired state of a Role.

FIELDS:
  deletionPolicy        <string>
  enum: Orphan, Delete
    DeletionPolicy specifies what will happen to the underlying external when
    this managed resource is deleted - either "Delete" or "Orphan" the external
    resource.

  forProvider   <Object> -required-
    RoleParameters define the desired state of a PostgreSQL role instance.

  providerConfigRef     <Object>
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.

  providerRef   <Object>
    ProviderReference specifies the provider that will be used to create,
    observe, update, and delete this managed resource. Deprecated: Please use
    ProviderConfigReference, i.e. `providerConfigRef`

  publishConnectionDetailsTo    <Object>
    PublishConnectionDetailsTo specifies the connection secret config which
    contains a name, metadata and a reference to secret store config to which
    any connection details for this managed resource should be written.
    Connection details frequently include the endpoint, username, and password
    required to connect to the managed resource.

  writeConnectionSecretToRef    <Object>
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should be
    written. Connection details frequently include the endpoint, username, and
    password required to connect to the managed resource. This field is planned
    to be replaced in a future release in favor of PublishConnectionDetailsTo.
    Currently, both could be set independently and connection details would be
    published to both without affecting each other.
```

### How could Crossplane help solve your problem?

Adding `managementPolicies` to the provider would be the ideal path forward. Aligning the docs with the reality of the project would still be an improvement though.

### PR DESCRIPTION
**Pull request by fernandezcuesta**
### Description of your changes
Add support for management policies.
Add maxReconcileRate argument.
~Bump golangci, remove deprecated linters and omit failing ones (mostly due to old runtime).~ offloaded to #216 

Fixes #206 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

make run

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by Duologic** [comment]
Would you mind splitting of the linter changes into a separate PR?

**Comment by fernandezcuesta** [comment]
@Duologic done! Moved the golangci changes to #216

**Comment by chkp-orhaz** [comment]
Hi All,
Is there any update, or ETA on when this will get implemented?

File: cmd/provider/main.go [hunk 1]
```diff
@@ -55,24 +61,44 @@ func main() {
...
-		LeaderElectionID: "crossplane-leader-election-provider-sql",
+	mgr, err := ctrl.NewManager(ratelimiter.LimitRESTConfig(cfg, *maxReconcileRate), ctrl.Options{
+		// SyncPeriod in ctrl.Options has been removed since controller-runtime v0.16.0
+		// The recommended way is to move it to cache.Options instead
 		Cache: cache.Options{
-			SyncPeriod: syncPeriod,
+			SyncPeriod: syncInterval,
 		},
+
+		// controller-runtime uses both ConfigMaps and Leases for leader
```
Comment (chlunde) [inline cmd/provider/main.go:76]: Could you split out this as a separate PR?

(After we get the CI fixes in)

Comment (fernandezcuesta) [reply cmd/provider/main.go]: removed!

**Review by chlunde — APPROVED** [review]
